import os.path

Import("env")

# TEST SUITES

testenv    = env.Clone()

testenv.Append( CPPPATH=[testenv['foundationpath'] + '/test'] )
testenv.Append( LIBPATH=['#/lib/${platform}${platformsuffix}/${buildprofile}'] )
testenv.Append( LIBS=[ 'test', 'foundation' ] )

if testenv['platform'] == 'linux':
	testenv.Append( LIBS=[ 'dl', 'rt', 'm' ] )
elif testenv['platform'] == 'raspberrypi':
	testenv.Append( LIBS=[ 'bcm_host', 'rt', 'm' ] )

def makeTest( name ):
    global env
    global testenv
    env[name + 'test'] = testenv.Program( 'test-' + name + '${prgsuffix}', name + '/main.c' )
    testenv.AddPostAction( 'test-' + name + '${prgsuffix}', testenv.Install( '#bin/${platform}${platformsuffix}/${buildprofile}', [ env[name + 'test'] ] ) )

makeTest('all')
makeTest('vector')
makeTest('matrix')
makeTest('quaternion')
