
import os.path

Import("env")


# SOURCES

vectorsources = [

	]

vectorheaders = [

	'types.h', 'vector.h'

	]


# ADD INTERNAL FLAGS

libenv = env.Clone()
libenv.Append( CPPDEFINES=['VECTOR_COMPILE=1'] )


# OUTPUTS

env['vectorlib'] = libenv.StaticLibrary( 'vector', vectorsources )


# DEPENDENCIES

#if env['toolset'] == 'gnu':
#	libenv.Depends( [ os.path.splitext( x )[0] + '.o' for x in vectorsources ], '#/vector/vector.h.gch' )


# INSTALLS

libenv.AddPostAction( 'vector', libenv.Install( '#lib/${platform}${platformsuffix}/${buildprofile}', [ env['vectorlib'] ] ) )
