import os.path

Import("env")


toolsenv    = env.Clone()

toolsenv.Append( CPPPATH=['#/tools'] )
toolsenv.Append( LIBPATH=['#/lib/${platform}${platformsuffix}/${buildprofile}'] )
toolsenv.Append( LIBS=[ 'vector', 'foundation' ] )

if toolsenv['platform'] == 'linux':
	toolsenv.Append( LIBS=[ 'dl', 'rt', 'm' ] )
elif toolsenv['platform'] == 'raspberrypi':
	toolsenv.Append( LIBS=[ 'bcm_host', 'rt', 'm' ] )

env['maskgenprg'] = toolsenv.Program( 'bin/maskgen${prgsuffix}', 'maskgen/main.c' )


# INSTALLS

toolsenv.AddPostAction( 'bin/maskgen${prgsuffix}', toolsenv.Install( '#bin/${platform}${platformsuffix}/${buildprofile}', [ env['maskgenprg'] ] ) )
